### ISSUE TITLE
No way to pass pre_process_handler to Xslate

### ISSUE THREAD

**Issue by madsen** [lestrrat/Catalyst-View-Xslate#22]
Catalyst::View::Xslate doesn't have a `pre_process_handler` attribute, so there's no easy way to set one for Text::Xslate.

Maybe there should just be an `additional_xslate_args` hash.  That way, you wouldn't need to update Catalyst::View::Xslate any time Text::Xslate got a new configuration option.

I've worked around this with an `around` handler on `_build_xslate`, but that's poking into the internals in a way I'd like to avoid.

**Comment by lestrrat** [comment]
I guess `pre_process_handler` had been there, but not released.

https://github.com/lestrrat/Catalyst-View-Xslate/blob/master/lib/Catalyst/View/Xslate.pm#L137

git blame says it was added in Feb 2015, but I didn't realize it was new, so I failed to mention it in the Changes file for 0.00019 release.
